server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.haizwang.recommend.springbootrecommendtestplat.model.po
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

PicturePath:
  url:D:/
#security:
#  basic:
#    enabled: false

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      enabled: true

devtools:
  restart:
    enabled: true  #设置开启热部署
    additional-paths: src/main/java #重启目录
    exclude: WEB-INF/**
    mode: LEGACYHTML5




